name: Build and Store Artifact

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - name: checkout code
         uses: actions/checkout@v3

       - name: Build project
         run: |
           mkdir -p output
           ls -lh > output/artifacts.txt
           ls -l output/
           cat output/artifacts.txt
       - name: upload artifact
         uses: actions/upload-artifact@v4
         with:
           name: my-artifact
           path: output/
  download:
     runs-on: ubuntu-latest
     needs: build
     steps:
        - name: Dowmload artifact from github actions
          uses: actions/download-artifact@v4
          with:
            name: my-artifact
            path: downloaded-artifact
        - name: List downloaded files
          run: ls -l downloaded-artifact/

        - name: Display artifact content
          run: cat downloaded-artifact/artifacts.txt

     
         

  
